### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by ukmadlz** [awe-der/aweder-core#2]
**Describe the bug**
Lacking the relevant License file

**To Reproduce**

**Expected behavior**
A LICENSE file should exist in the root stating exactly what rights and controls people have over the software

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SecondeJK** [comment]
fixed in #7 by linking to MIT license in docs
